# DuckyWM Configuration

border_width = 2
gap_size = 8

# Keyboard layout language (X11 only; Wayland uses compositor config)
keyboard_layout = de

# Hotkeys
key_terminal = Return
key_close = q
key_left = h
key_right = l
key_settings = s
key_files = f
key_quit = e
reloadconfig = r

# Theme: Dark Tealish background & Normal Tealish elements
background = #031414
normal_border = #0b3b3b
focused_border = #126363
topbar_background = #072626

# Terminal Theme: Solid Black
terminal_background = #000000
terminal_foreground = #d8ffff
terminal_cursor = #126363
terminal = xterm
