# DuckyWM configuration

border_width = 2
gap_size = 8

background = #073b3b
normal_border = #164e4e
focused_border = #20c4c4

terminal_background = #102828
terminal_foreground = #d8ffff
terminal_cursor = #20c4c4
terminal = xterm
